[tool.poetry]
name = "imagopixel"
version = "0.1.0"
description = ""
authors = ["NekrodNIK"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Pillow = "^9.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
